export const seedFields = [
  {
    id: "field-1",
    name: "Field A",
    area: "12.5 hectares",
    crop: "Winter Wheat",
    health: 85,
    lastUpdated: "2024-09-18T14:30:00Z",
    coordinates: [
      { lat: 30.901, lng: 75.857 },
      { lat: 30.903, lng: 75.859 },
      { lat: 30.904, lng: 75.856 },
      { lat: 30.902, lng: 75.854 },
    ],
  },
  {
    id: "field-2",
    name: "Field B",
    area: "8.2 hectares",
    crop: "Corn",
    health: 67,
    lastUpdated: "2024-09-18T13:15:00Z",
    coordinates: [
      { lat: 30.899, lng: 75.854 },
      { lat: 30.9, lng: 75.852 },
      { lat: 30.898, lng: 75.85 },
      { lat: 30.897, lng: 75.852 },
    ],
  },
  {
    id: "field-3",
    name: "Field C",
    area: "6.8 hectares",
    crop: "Soybeans",
    health: 92,
    lastUpdated: "2024-09-18T14:25:00Z",
    coordinates: [
      { lat: 30.905, lng: 75.861 },
      { lat: 30.906, lng: 75.863 },
      { lat: 30.907, lng: 75.859 },
      { lat: 30.904, lng: 75.858 },
    ],
  },
];

export const seedSensors = [
  {
    id: "sensor-1",
    name: "Soil Moisture Sensor A1",
    type: "soil_moisture",
    location: "Field A - Section 1",
    status: "online",
    battery: 85,
    lastReading: "2024-09-18T14:30:00Z",
    value: 42,
    unit: "%",
    optimal: { min: 35, max: 65 },
    coordinates: { lat: 30.901, lng: 75.857 },
    fieldId: "field-1",
  },
  {
    id: "sensor-2",
    name: "Temperature Sensor A2",
    type: "temperature",
    location: "Field A - Section 2",
    status: "online",
    battery: 92,
    lastReading: "2024-09-18T14:28:00Z",
    value: 24.5,
    unit: "°C",
    optimal: { min: 18, max: 28 },
    coordinates: { lat: 30.903, lng: 75.859 },
    fieldId: "field-1",
  },
  {
    id: "sensor-3",
    name: "pH Sensor B1",
    type: "ph",
    location: "Field B - Section 1",
    status: "warning",
    battery: 23,
    lastReading: "2024-09-18T13:15:00Z",
    value: 6.8,
    unit: "pH",
    optimal: { min: 6.0, max: 7.5 },
    coordinates: { lat: 30.899, lng: 75.854 },
    fieldId: "field-2",
  },
  {
    id: "sensor-4",
    name: "Soil Moisture Sensor B2",
    type: "soil_moisture",
    location: "Field B - Section 2",
    status: "offline",
    battery: 0,
    lastReading: "2024-09-17T09:22:00Z",
    value: 28,
    unit: "%",
    optimal: { min: 35, max: 65 },
    coordinates: { lat: 30.897, lng: 75.852 },
    fieldId: "field-2",
  },
  {
    id: "sensor-5",
    name: "NPK Sensor C1",
    type: "npk",
    location: "Field C - Section 1",
    status: "online",
    battery: 67,
    lastReading: "2024-09-18T14:25:00Z",
    value: 185,
    unit: "ppm",
    optimal: { min: 150, max: 300 },
    coordinates: { lat: 30.905, lng: 75.861 },
    fieldId: "field-3",
  },
];

export const seedMerchants = [
  {
    id: "merchant-1",
    name: "Raj Agro Trading",
    company: "Raj Agro Pvt Ltd",
    location: "Pune, Maharashtra",
    distance: "12 km",
    rating: 4.5,
    phone: "+91 98765 43210",
    specialties: ["Wheat", "Rice", "Pulses"],
    crops: [
      { name: "Wheat", price: 2150, unit: "quintal", demand: "high" },
      { name: "Rice", price: 3200, unit: "quintal", demand: "medium" },
      { name: "Chickpea", price: 5800, unit: "quintal", demand: "high" },
    ],
    verified: true,
  },
  {
    id: "merchant-2",
    name: "Green Valley Foods",
    company: "Green Valley Processing",
    location: "Nashik, Maharashtra",
    distance: "25 km",
    rating: 4.2,
    phone: "+91 98765 43211",
    specialties: ["Vegetables", "Fruits", "Organic"],
    crops: [
      { name: "Tomato", price: 25, unit: "kg", demand: "high" },
      { name: "Onion", price: 18, unit: "kg", demand: "medium" },
      { name: "Potato", price: 15, unit: "kg", demand: "low" },
    ],
    verified: true,
  },
  {
    id: "merchant-3",
    name: "Maharashtra Cotton Corp",
    company: "Cotton Corporation of India",
    location: "Aurangabad, Maharashtra",
    distance: "45 km",
    rating: 4.8,
    phone: "+91 98765 43212",
    specialties: ["Cotton", "Sugarcane"],
    crops: [
      { name: "Cotton", price: 6200, unit: "quintal", demand: "high" },
      { name: "Sugarcane", price: 350, unit: "quintal", demand: "medium" },
    ],
    verified: true,
  },
];

export const seedCropDemand = [
  {
    id: "demand-1",
    crop: "Wheat",
    avgPrice: 2180,
    merchants: 8,
    trend: "up",
    recommendation: "High demand due to festival season. Best time to sell.",
    lastUpdated: "2024-09-18T12:00:00Z",
  },
  {
    id: "demand-2",
    crop: "Rice",
    avgPrice: 3150,
    merchants: 6,
    trend: "stable",
    recommendation: "Stable prices. Good time for bulk sales.",
    lastUpdated: "2024-09-18T12:00:00Z",
  },
  {
    id: "demand-3",
    crop: "Cotton",
    avgPrice: 6350,
    merchants: 4,
    trend: "up",
    recommendation: "Export demand increasing. Premium prices available.",
    lastUpdated: "2024-09-18T12:00:00Z",
  },
  {
    id: "demand-4",
    crop: "Tomato",
    avgPrice: 28,
    merchants: 12,
    trend: "down",
    recommendation: "Oversupply in market. Consider processed sales.",
    lastUpdated: "2024-09-18T12:00:00Z",
  },
];

export const seedPolls = [
  {
    id: "poll-1",
    title: "Best Crop for Rabi Season 2024",
    description: "Help fellow farmers decide which crop has the best potential for the upcoming Rabi season based on market trends and weather predictions.",
    category: "crop_selection",
    status: "active",
    creator: "Agricultural Expert Dr. Patel",
    createdAt: "2024-03-10",
    endDate: "2024-03-25",
    region: "Maharashtra",
    options: [
      { id: "poll-1a", text: "Wheat", votes: 89 },
      { id: "poll-1b", text: "Barley", votes: 56 },
      { id: "poll-1c", text: "Chickpea", votes: 67 },
      { id: "poll-1d", text: "Mustard", votes: 22 },
    ],
  },
  {
    id: "poll-2",
    title: "Fair Price for Tomatoes This Season",
    description: "What do you think is a fair price for tomatoes considering current market conditions?",
    category: "pricing",
    status: "active",
    creator: "Farmers Collective Pune",
    createdAt: "2024-03-12",
    endDate: "2024-03-20",
    region: "Maharashtra",
    options: [
      { id: "poll-2a", text: "₹20-25 per kg", votes: 62 },
      { id: "poll-2b", text: "₹25-30 per kg", votes: 47 },
      { id: "poll-2c", text: "₹30-35 per kg", votes: 31 },
      { id: "poll-2d", text: "Above ₹35 per kg", votes: 16 },
    ],
  },
  {
    id: "poll-3",
    title: "Most Effective Organic Fertilizer",
    description: "Share your experience with organic fertilizers. Which one has given you the best results?",
    category: "technique",
    status: "active",
    creator: "Green Farming Initiative",
    createdAt: "2024-03-08",
    endDate: "2024-03-30",
    region: "All India",
    options: [
      { id: "poll-3a", text: "Vermicompost", votes: 34 },
      { id: "poll-3b", text: "FYM (Farm Yard Manure)", votes: 28 },
      { id: "poll-3c", text: "Compost", votes: 19 },
      { id: "poll-3d", text: "Bio-fertilizer", votes: 8 },
    ],
  },
  {
    id: "poll-4",
    title: "Cotton Market Outlook",
    description: "How do you see the cotton market performing in the next 6 months?",
    category: "market_trend",
    status: "completed",
    creator: "Cotton Association of India",
    createdAt: "2024-02-15",
    endDate: "2024-03-01",
    region: "All India",
    options: [
      { id: "poll-4a", text: "Prices will increase", votes: 165 },
      { id: "poll-4b", text: "Prices will remain stable", votes: 124 },
      { id: "poll-4c", text: "Prices will decrease", votes: 82 },
      { id: "poll-4d", text: "Uncertain/Volatile", votes: 41 },
    ],
  },
];

export const seedDatasetMetadata = [
  {
    key: "farm-fields",
    version: "1.0.0",
    lastUpdated: "2024-09-18T14:30:00Z",
    source: "Seeded operational data",
    notes: "Baseline field health snapshot for demo accounts.",
  },
  {
    key: "farm-sensors",
    version: "1.0.0",
    lastUpdated: "2024-09-18T14:30:00Z",
    source: "Seeded operational data",
    notes: "Sensor telemetry for pilot farms.",
  },
  {
    key: "market-merchants",
    version: "1.0.0",
    lastUpdated: "2024-09-18T12:00:00Z",
    source: "Seeded merchant directory",
  },
  {
    key: "market-demand",
    version: "1.0.0",
    lastUpdated: "2024-09-18T12:00:00Z",
    source: "Seeded demand intelligence",
  },
  {
    key: "community-polls",
    version: "1.0.0",
    lastUpdated: "2024-03-30T12:00:00Z",
    source: "Seeded community polls",
  },
  {
    key: "weather-snapshots",
    version: "1.0.0",
    lastUpdated: "2024-09-18T12:00:00Z",
    source: "OpenWeatherMap ingestion",
    notes: "Scheduled weather snapshots for alerting.",
  },
  {
    key: "mandi-prices",
    version: "1.0.0",
    lastUpdated: "2024-09-18T12:00:00Z",
    source: "Mandi ingestion pipeline",
    notes: "Market price ingestion for alerts.",
  },
];
