// Firebase configuration
// This file is automatically generated. Do not edit it directly.

import { initializeApp, FirebaseError } from "firebase/app";
import { getAuth, RecaptchaVerifier, signInWithPhoneNumber, ConfirmationResult, User, onAuthStateChanged as firebaseOnAuthStateChanged } from "firebase/auth";

// Load Firebase config from environment variables
const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY || "",
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || "",
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || "",
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || "",
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || "",
  appId: import.meta.env.VITE_FIREBASE_APP_ID || "",
  measurementId: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID || ""
};

// Initialize Firebase with error handling
let app: any = null;
let auth: any = null;
let confirmationResultGlobal: ConfirmationResult | null = null;

try {
  // Validate Firebase config is available
  if (!firebaseConfig.apiKey) {
    console.error("CRITICAL: Firebase API key is not configured. Set VITE_FIREBASE_API_KEY in your .env file.");
  }
  app = initializeApp(firebaseConfig);
  auth = getAuth(app);
} catch (error) {
  console.error("Firebase initialization error:", error);
}

// Firebase Authentication Helper
export const FirebaseAuth = {
  // Check if Firebase is initialized
  isAvailable: (): boolean => {
    return auth !== null;
  },

  // Initialize Recaptcha
  initRecaptcha: (containerId: string): RecaptchaVerifier | null => {
    if (!auth) return null;
    try {
      const recaptchaVerifier = new RecaptchaVerifier(auth, containerId, {
        size: 'invisible',
        callback: () => {},
        'expired-callback': () => {}
      });
      recaptchaVerifier.render();
      return recaptchaVerifier;
    } catch (error) {
      console.error("Recaptcha error:", error);
      return null;
    }
  },

  // Send OTP to phone number
  sendOTP: async (phoneNumber: string, containerId: string): Promise<ConfirmationResult> => {
    if (!auth) {
      throw new Error("Firebase is not available. Please refresh the page.");
    }

    try {
      let recaptchaContainer = document.getElementById(containerId);
      if (!recaptchaContainer) {
        recaptchaContainer = document.createElement("div");
        recaptchaContainer.id = containerId;
        recaptchaContainer.style.display = "none";
        document.body.appendChild(recaptchaContainer);
      }

      const recaptchaVerifier = FirebaseAuth.initRecaptcha(containerId);
      if (!recaptchaVerifier) {
        throw new Error("Failed to initialize reCAPTCHA");
      }
      
      const result = await signInWithPhoneNumber(auth, phoneNumber, recaptchaVerifier);
      confirmationResultGlobal = result;
      return result;
    } catch (error: any) {
      console.error("Error sending OTP:", error);
      throw error;
    }
  },

  // Verify OTP code
  verifyOTP: async (otpCode: string): Promise<User | null> => {
    if (!confirmationResultGlobal) {
      throw new Error("No confirmation result found. Please request a new OTP.");
    }

    try {
      const result = await confirmationResultGlobal.confirm(otpCode);
      return result.user;
    } catch (error) {
      console.error("Error verifying OTP:", error);
      throw error;
    }
  },

  // Get current user
  getCurrentUser: (): User | null => {
    return auth?.currentUser || null;
  },

  // Sign out
  signOut: async (): Promise<void> => {
    if (auth) {
      const { signOut: firebaseSignOut } = await import("firebase/auth");
      await firebaseSignOut(auth);
    }
    confirmationResultGlobal = null;
    localStorage.removeItem("firebase_confirmation");
    localStorage.removeItem("farmer_user");
  },

  // Listen to auth state changes
  onAuthStateChanged: (callback: (user: User | null) => void): (() => void) => {
    if (!auth) {
      // Return a no-op unsubscribe if auth is not available
      return () => {};
    }
    return firebaseOnAuthStateChanged(auth, callback);
  }
};

export { auth, app };
export default app;
