// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function userClient(ctx) {
  return createClient("https://exynaicvgadoenjfunqz.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4eW5haWN2Z2Fkb2VuamZ1bnF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NzUwNjgsImV4cCI6MjA4ODM1MTA2OH0.T-xiyOGqzXkfFrg1FxsRyb6f_ErMMKGH8CmBOyVqgu8", {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in KrishiSarthi user's profile (name, phone, location, role).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = userClient(ctx);
    const uid = ctx.getUserId();
    const [{ data: profile, error: pErr }, { data: roles }] = await Promise.all([
      sb.from("profiles").select("display_name, email, phone, location").eq("user_id", uid).maybeSingle(),
      sb.from("user_roles").select("role").eq("user_id", uid)
    ]);
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    const result = { ...profile, roles: (roles || []).map((r) => r.role) };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function userClient2(ctx) {
  return createClient2("https://exynaicvgadoenjfunqz.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4eW5haWN2Z2Fkb2VuamZ1bnF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NzUwNjgsImV4cCI6MjA4ODM1MTA2OH0.T-xiyOGqzXkfFrg1FxsRyb6f_ErMMKGH8CmBOyVqgu8", {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_notifications_default = defineTool2({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "List the signed-in user's KrishiSarthi notifications (weather, crop tasks, market alerts). Most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max notifications to return (default 10)."),
    unread_only: z.boolean().optional().describe("If true, return only unread notifications.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, unread_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = userClient2(ctx).from("notifications").select("id, title, message, type, is_read, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (unread_only) q = q.eq("is_read", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-crop-plans.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function userClient3(ctx) {
  return createClient3("https://exynaicvgadoenjfunqz.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4eW5haWN2Z2Fkb2VuamZ1bnF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NzUwNjgsImV4cCI6MjA4ODM1MTA2OH0.T-xiyOGqzXkfFrg1FxsRyb6f_ErMMKGH8CmBOyVqgu8", {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_crop_plans_default = defineTool3({
  name: "list_my_crop_plans",
  title: "List my crop plans",
  description: "List the signed-in farmer's crop plans (crop, season, sowing date, expected harvest, area).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await userClient3(ctx).from("crop_plans").select("*").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { crop_plans: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-field-event.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function userClient4(ctx) {
  return createClient4("https://exynaicvgadoenjfunqz.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4eW5haWN2Z2Fkb2VuamZ1bnF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NzUwNjgsImV4cCI6MjA4ODM1MTA2OH0.T-xiyOGqzXkfFrg1FxsRyb6f_ErMMKGH8CmBOyVqgu8", {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_field_event_default = defineTool4({
  name: "log_field_event",
  title: "Log a field event",
  description: "Record a field activity (irrigation, fertilizer, pesticide, sowing, harvest, observation) for the signed-in farmer.",
  inputSchema: {
    event_type: z2.enum(["irrigation", "fertilizer", "pesticide", "sowing", "harvest", "observation", "other"]).describe("Kind of field activity."),
    notes: z2.string().min(1).describe("Short description of what happened."),
    crop: z2.string().optional().describe("Optional crop name this event relates to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ event_type, notes, crop }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await userClient4(ctx).from("field_events").insert({
      user_id: ctx.getUserId(),
      event_type,
      notes,
      crop: crop ?? null,
      event_date: (/* @__PURE__ */ new Date()).toISOString()
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${event_type} event.` }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "exynaicvgadoenjfunqz";
var mcp_default = defineMcp({
  name: "krishisarthi-mcp",
  title: "KrishiSarthi MCP",
  version: "0.1.0",
  instructions: "Tools for KrishiSarthi, the Indian farmer assistant. Read the signed-in user's profile, notifications, and crop plans, and log field events (irrigation, fertilizer, sowing, harvest, observations). All calls act as the authenticated user and respect existing row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_notifications_default, list_crop_plans_default, log_field_event_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
