// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// DO NOT USE HARDCODED KEYS - Use environment variables instead
// Set VITE_SUPABASE_URL and either VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY in your .env file
const resolvedSupabaseUrl = SUPABASE_URL;
const resolvedSupabaseKey = SUPABASE_PUBLISHABLE_KEY || SUPABASE_ANON_KEY;

export const hasSupabaseEnv = Boolean(resolvedSupabaseUrl && resolvedSupabaseKey);

if (!SUPABASE_URL || !resolvedSupabaseKey) {
  console.error(
    'CRITICAL: Supabase environment variables are missing. Required: VITE_SUPABASE_URL and one of VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY.',
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safely create client only if both credentials are available
export const supabase = resolvedSupabaseUrl && resolvedSupabaseKey 
  ? createClient<Database>(resolvedSupabaseUrl, resolvedSupabaseKey, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : null;
