// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// DO NOT USE HARDCODED KEYS - Use environment variables instead
// Set VITE_SUPABASE_URL and either VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY in your .env file
const resolvedSupabaseUrl = SUPABASE_URL;
const resolvedSupabaseKey = SUPABASE_PUBLISHABLE_KEY || SUPABASE_ANON_KEY;

export const hasSupabaseEnv = Boolean(
  resolvedSupabaseUrl && 
  resolvedSupabaseKey && 
  !resolvedSupabaseUrl.includes("<project-ref>") &&
  !resolvedSupabaseUrl.includes("mockproject") &&
  !resolvedSupabaseKey.includes("<supabase-anon-key>")
);

if (!SUPABASE_URL || !resolvedSupabaseKey) {
  console.error(
    'CRITICAL: Supabase environment variables are missing. Required: VITE_SUPABASE_URL and one of VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY.',
  );
}

// Create a safe mock channel structure
const createMockChannel = () => {
  const mockChannel: any = {
    on: (event: string, filter: any, callback?: any) => {
      console.debug(`[Mock Channel] .on called for event: ${event}`);
      return mockChannel;
    },
    subscribe: () => {
      console.debug("[Mock Channel] .subscribe called");
      return mockChannel;
    },
    unsubscribe: () => {
      console.debug("[Mock Channel] .unsubscribe called");
      return Promise.resolve();
    }
  };
  return mockChannel;
};

// Create safe query builder for mock client
const createMockQueryBuilder = () => {
  const queryBuilder: any = new Proxy({}, {
    get(target, method) {
      if (method === 'then') {
        return (resolve: any) => resolve({ data: [], error: null });
      }
      if (method === 'single' || method === 'maybeSingle') {
        return () => Promise.resolve({ data: null, error: null });
      }
      if (method === 'insert' || method === 'upsert' || method === 'update' || method === 'delete') {
        return () => Promise.resolve({ data: null, error: null });
      }
      return () => queryBuilder;
    }
  });
  return queryBuilder;
};

let rawSupabase: any = null;
try {
  rawSupabase = resolvedSupabaseUrl && resolvedSupabaseKey 
    ? createClient<Database>(resolvedSupabaseUrl, resolvedSupabaseKey, {
        auth: {
          storage: typeof window !== 'undefined' ? window.localStorage : undefined,
          persistSession: true,
          autoRefreshToken: true,
        }
      })
    : null;
} catch (err) {
  console.error("Failed to initialize real Supabase client:", err);
}

// Wrap the real client or create a mock client proxy
export const supabase = (() => {
  if (rawSupabase) {
    // Wrap channel method on real client to catch any runtime exceptions
    const originalChannel = rawSupabase.channel.bind(rawSupabase);
    rawSupabase.channel = (name: string, opts?: any) => {
      try {
        const chan = originalChannel(name, opts);
        if (chan && typeof chan.on === 'function') {
          return chan;
        }
      } catch (err) {
        console.error("Failed to create real Supabase channel, falling back to mock channel:", err);
      }
      return createMockChannel();
    };

    // Wrap removeChannel on real client to catch exceptions
    const originalRemoveChannel = rawSupabase.removeChannel.bind(rawSupabase);
    rawSupabase.removeChannel = (channel: any) => {
      try {
        return originalRemoveChannel(channel);
      } catch (err) {
        console.error("Failed to remove Supabase channel:", err);
        return Promise.resolve();
      }
    };

    return rawSupabase;
  }

  // Fallback Proxy Client
  return new Proxy({}, {
    get(target, prop) {
      if (prop === 'auth') {
        return {
          getSession: async () => ({ data: { session: null }, error: null }),
          getUser: async () => ({ data: { user: null }, error: null }),
          signOut: async () => ({ error: null }),
          onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
          signUp: async () => ({ data: { user: null, session: null }, error: new Error("Supabase is not connected. Did you forget to restart the development server after saving environment variables?") }),
          signInWithPassword: async () => ({ data: { user: null, session: null }, error: new Error("Supabase is not connected. Did you forget to restart the development server after saving environment variables?") }),
          updateUser: async () => ({ data: { user: null }, error: new Error("Supabase not connected") }),
          resetPasswordForEmail: async () => ({ data: {}, error: new Error("Supabase not connected") }),
          refreshSession: async () => ({ data: { session: null, user: null }, error: null }),
        };
      }
      if (prop === 'functions') {
        return {
          invoke: async () => ({ data: { success: true, verified: true }, error: null }),
        };
      }
      if (prop === 'channel') {
        return () => createMockChannel();
      }
      if (prop === 'removeChannel') {
        return () => Promise.resolve();
      }
      if (prop === 'from') {
        return () => createMockQueryBuilder();
      }
      if (prop === 'rpc') {
        return () => Promise.resolve({ data: null, error: null });
      }
      return () => {};
    }
  }) as any;
})();
